services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: tenantvault-db
    command: >
      postgres
      -c shared_preload_libraries=pgaudit
      -c pgaudit.log=write,ddl
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tenantvault
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

volumes:
  pgdata: